############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2

[[main]]
name = "Categories"
url = "/categories"
weight = 3




# footer menu
#[[footer]]
#name = "About"
#url = "/about"
#weight = 1

#[[footer]]
#name = "Elements"
#url = "/elements"
#weight = 2

#[[footer]]
#name = "Privacy Policy"
#url = "/privacy-policy"
#weight = 3